// import Head from 'next/head'
// import styles from '../../styles/Home.module.css'
// import { Abril_Fatface } from '@next/font/google'

// const abril_fatface = Abril_Fatface({ weight: ['400'], subsets: ['latin'] })

// export default function Activities() {
//   const postData = async () => {

//   }
  
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Agora</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={abril_fatface.className}>
//           Agora
//         </h1>
//         <p>Which activity will you partake in?</p>

        
//         <button onClick={postData}>Post an Activity</button>
//       </main>
//     </div>
//   )
// }
